logFile='d:/dev/ironcar/ironcarAgfa/sport-ironcar/output/outputRenderer/render_log.txt'
renderedImageFile='d:/dev/ironcar/ironcarAgfa/sport-ironcar/output/outputRenderer/road.png'
detectionFile='d:/dev/ironcar/ironcarAgfa/sport-ironcar/output/outputAnalyser/detection.json'
commandFile='d:/dev/ironcar/ironcarAgfa/sport-ironcar/output/outputAnalyser/command.json'
gameOutputFile='d:/dev/ironcar/ironcarAgfa/sport-ironcar/output/outputRenderer/result.json'
gamesDir='d:/dev/ironcar/ironcarAgfa/sport-ironcar/output/games/'
analyzerDebugDir='d:/dev/ironcar/output/debug/png'
videoDebugDir = "d:/dev/ironcar/output/debug/video"
rnCheckpointsFile = "d:/dev/ironcar/output/debug/rn"
carLocation = 'd:/dev/ironcar/ironcarAgfa/sport-ironcar/output/outputRenderer/carLocation.json'
gameEngineExecutable = "‪d:\\dev\\ironcar\\ironcarAgfa\\sport-ironcar\\blender\\roadGameEngine.exe"